Tellat2/Components/ViewModels/CommentComponentViewModel.cs
using System.Collections.Generic;
using Framework2.Core.Models.Core;
using Tellat2.Base;

namespace Tellat2.Components.ViewModels
{
    /// <summary>
    /// Provides the category component controller with data binding
    /// </summary>
    public class CommentComponentViewModel : BaseViewModel
    {
        public int ReportId { get; set; }
        public string Text { get; set; }

        public List<Comment> Comments { get; set; }
    }
}

Tellat2/Components/Controllers/CommentComponentController.cs
using System.Linq;
using System.Web.Mvc;
using Framework2.Core.Repositories.Base;
using Framework2.Core.Repositories.Core.Interfaces;
using Framework2.Core.Services.Interfaces;
using Microsoft.Practices.Unity;
using Tellat2.Base;
using Tellat2.Components.ViewModels;

namespace Tellat2.Components.Controllers
{
    /// <summary>
    /// Encapsulates the commenting functionality in to a re-useable component
    /// </summary>
    public class CommentComponentController : BaseController<CommentComponentViewModel>
    {
        [Dependency]
        public ICommentService CommentService { get; set; }

        [Dependency]
        public ICommentRepository CommentRepository { get; set; }

        /// <summary>
        /// /CommentComponent/Index
        /// </summary>
        public ActionResult Index(int reportId)
        {
            try
            {
                ViewModel.Comments = CommentRepository.FindAllByReportId(reportId).ToList();
            }
            catch (RepositoryException)
            {

            }

            return PartialView("_Index", ViewModel);
        }

        /// <summary>
        /// /CommentComponent/Post
        /// </summary>
        public ActionResult Post(CommentComponentViewModel model)
        {
            try
            {
                CommentService.Create(CurrentUserId, model.ReportId, model.Text);

                model.Comments = CommentRepository.FindAllByReportId(model.ReportId).ToList();
                model.Text = string.Empty;
            }
            catch (RepositoryException ex)
            {
                
            }

            return PartialView("_Index", model);
        }
    }
}

Tellat2/Components/Views/CommentComponent/_Index.cshtml
@using Tellat2.Extensions
@using Framework2.Core.Extensions
@model Tellat2.Components.ViewModels.CommentComponentViewModel

@Styles.Render("~/Content/componentComment")

<!-- Comments widget -->
<div id="comment-component">

    <h1>Comments</h1>

    <!-- Comments -->
    <div id="comment-list">
        @foreach (var item in @Model.Comments)
        {
            <div class="item">
                <div class="text-area">
                    <span class="time-span">@item.CreationDate.ToRelativeDate()</span>
                    @{if (@item.ApplicationUser == null)
                    {
                        <img class="profile-image" src="~/Content/Images/Pages/Shared/user.png" alt="anonymous user" />
                        <img class="profile-overlay" src="~/Content/Images/Components/Comment/circle-small.png" alt="overlay" />
                        <div class="title">Anonymous</div>
                    }
                    else
                    {
                        <img class="profile-image" src="@item.ApplicationUser.ThumbnailPath()" alt="@item.ApplicationUser.UserName" />
                        <img class="profile-overlay" src="~/Content/Images/Components/Comment/circle-small.png" alt="overlay" />
                        <div class="title">@item.ApplicationUser.UserName</div>
                    }
                    }
                    <div class="sub-title">
                        @item.Text
                    </div>
                </div>
            </div>
        }
    </div>



                <!-- Form -->
                @*@if (Model.IsLoggedIn) This is commented out to allow comments from non-logged in users
                    {*@
                <div id="entry-box">
                    @using (Ajax.BeginForm("Post", "CommentComponent", null, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "comment-component" }))
            {
                        <fieldset>
                            @Html.ValidationMessageFor(m => m.Text)

                            @Html.HiddenFor(m => m.ReportId)

                            @Html.TextAreaFor(m => m.Text, new { @id = "comment-area", placeholder = "Add your comment..." })
                            <div id="toolbar">
                                <input type="submit" value="Post" class="red-button" />
                            </div>
                        </fieldset>
            }
                </div>
                @*}*@

            </div>

            <!-- Ensure the comment box is empty and focussed -->
            <script>
                $('#comment-area').val("");
                $('#comment-area').focus();
            </script>